POST https://teamif.io:7000/auth/login
Content-Type: application/json

{
  "email": "asdf@naver.com",
  "pass": "asdf"
}

###
POST https://teamif.io:7000/auth/register
Content-Type: application/json

{
  "email": "assdf@naver.com",
  "pass": "asdf",
  "username": "asdfasdf"
}

###
POST https://teamif.io:7000/auth/register
Content-Type: application/json

{
  "email": "asdf@naver.com",
  "pass": "asdf",
  "username": "asdfasdf",
  "phonenumber": "+821011112222"
}

###